FROM ros:humble-ros-base-jammy
SHELL ["/bin/bash", "-c"]
ENV ROS_DISTRO=humble

##############################
# 1. Install system dependencies and build tools
##############################
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ninja-build \
    pkg-config \
    cmake \
    ros-${ROS_DISTRO}-dynamixel-sdk \
    ros-${ROS_DISTRO}-tf-transformations \
    ros-${ROS_DISTRO}-diagnostic-msgs \
    ros-${ROS_DISTRO}-robot-localization \
    python3 python3-pip python3-colcon-common-extensions \
    ros-${ROS_DISTRO}-example-interfaces ros-${ROS_DISTRO}-rclpy \
    python3-yaml python3-ply \
    python3-serial \
    python3-gpiozero python3-lgpio \
    git python3-jinja2 \
    libboost-dev libgnutls28-dev openssl libtiff5-dev pybind11-dev \
    libglib2.0-dev libgstreamer-plugins-base1.0-dev \
    libdrm-dev libexpat1-dev libjpeg-dev libpng-dev libcap-dev \
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    gstreamer1.0-plugins-base \
    python3-dev \
    python3-smbus \
    i2c-tools \
 && rm -rf /var/lib/apt/lists/*

##############################
# 2. Upgrade pip and install Python dependencies
##############################
RUN pip3 install --upgrade pip && \
    pip3 install meson

##############################
# 3. Clone and build libcamera with Python support
##############################
RUN mkdir /packages
WORKDIR /packages

RUN git clone https://github.com/raspberrypi/libcamera.git
WORKDIR /packages/libcamera

RUN meson setup build --buildtype=release \
    -Dpipelines=rpi/vc4,rpi/pisp \
    -Dipas=rpi/vc4,rpi/pisp \
    -Dv4l2=true \
    -Dgstreamer=enabled \
    -Dtest=false \
    -Dlc-compliance=disabled \
    -Dcam=disabled \
    -Dqcam=disabled \
    -Ddocumentation=disabled \
    -Dpycamera=enabled \
    -Dprefix=/usr

RUN ninja -C build
RUN ninja -C build install && ldconfig

##############################
# 4. Install additional Python packages
##############################
RUN pip3 install picamera2 opencv-python pyserial dynamixel-sdk smbus2
RUN pip3 install 'numpy<1.24.0'

##############################
# 5. Python and library paths
##############################
ENV PYTHONPATH="/usr/local/lib/python3.10/site-packages:/usr/local/lib/python3.10/dist-packages:/usr/local/lib/python3/dist-packages"
ENV PYTHONPATH="/usr/lib/python3/dist-packages:/usr/lib/python3.10/site-packages:${PYTHONPATH}"
ENV PYTHONPATH="/usr/lib/aarch64-linux-gnu/python3.10/site-packages:${PYTHONPATH}"

ENV LD_LIBRARY_PATH="/usr/local/lib/aarch64-linux-gnu"

##############################
# 6. Copy entrypoint and set it
##############################
COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
