# These are the parameters used for the camera localisation. Upon adding a new aruco code on the circuit, simply add its id number and its location here.
# test
# To get the aruco id, uncomment detect_aruco.py lines 144-145 or adapt code for local pc (change from picamera to cv.videocapture method)
localization_node: # needs to be the same name than the node where the config file is used
  ros__parameters:
    cam_params:
      lens_position: 1.59
      dist_cam_robot_center: 0
      aruco_square_size: 0.036
      camera_height: 0.63        # Height of the camera from the ground in meters
      fx: 1965.73                 # Focal length in pixels along the x-axis
      fy: 1964.48                 # Focal length in pixels along the y-axis
      #principal_x: 0.0      # Optical center x (if not, image_width/2)
      #principal_y: 0.0        # Optical center y (if not, image_height/2)
      angle_offset: 1.5708

    aruco_params:
      11:
        t_x: 4.352
        t_y: 6.368
        yaw: 0.0
      618:
        t_x: 4.402
        t_y: 7.358
        yaw: 0.0
      645:
        t_x: 0.0
        t_y: 0.0
        yaw: 0.0
      614:
        t_x: 4.38
        t_y: 4.56
        yaw: 0.0
      914:
        t_x: 1.0
        t_y: 1.0
        yaw: 0.0