ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 0.6         # Increased timeout to account for the slower (0.5 s) camera updates
    two_d_mode: true
    transform_time_offset: 0.0
    transform_timeout: 0.0
    publish_tf: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "odom"

    # High-rate wheel odometry (less trusted)
    odom0: "odomWheel"
    odom0_config: [true, true, false,   # x, y, yaw positions
                   false, false, true,   # yaw rate (angular velocity)
                   false, false, false,  # unused fields (z, roll, pitch)
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_pose_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

    # Lower-rate camera odometry (more trusted)
    pose0: "camera_pose"  # Now using the sensor message with covariance
    pose0_frame: "camera_frame"  # Ensure your sensor message header.frame_id matches this!
    pose0_config: [true, true, false,   # x, y, yaw positions
                   false, false, true,   # yaw rate (angular velocity)
                   false, false, false,  # unused fields (z, roll, pitch)
                   false, false, false,
                   false, false, false]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 10
    pose0_pose_covariance: [0.01, 0.0, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.01, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.01, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.01, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.01, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.0, 0.01]
