ekf_filter_node:
  ros__parameters:
    frequency: 30.0             # EKF update rate (Hz)
    sensor_timeout: 0.6         # Increased to accommodate the 0.5 s camera update period
    two_d_mode: true            # Restrict the filter to 2D (x, y, yaw)
    transform_time_offset: 0.0
    transform_timeout: 0.0
    publish_tf: true
    map_frame: "map"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "map"

    # High-rate wheel odometry (less trusted)
    odom0: "odomWheel"
    odom0_config: [true, true, false,   # x, y, yaw positions
                   false, false, true,   # yaw rate (angular velocity)
                   false, false, false,  # unused fields (z, roll, pitch)
                   false, false, false,
                   false, false, false]
    odom0_differential: false
    odom0_relative: false
    odom0_queue_size: 10
    odom0_pose_covariance: [0.1, 0.0, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.1, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.1, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.1, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.1, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.0, 0.1]

    # Lower-rate camera odometry (more trusted)
    pose0: "camera_pose"   # Use the sensor message published on "camera_pose"
    pose0_frame: "map"     # The measurement is now expressed in the map frame
    pose0_config: [true, true, false,   # x, y, yaw positions
                   false, false, true,   # yaw rate (angular velocity)
                   false, false, false,  # unused fields (z, roll, pitch)
                   false, false, false,
                   false, false, false]
    pose0_differential: false
    pose0_relative: false
    pose0_queue_size: 10
    pose0_pose_covariance: [0.01, 0.0, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.01, 0.0, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.01, 0.0, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.01, 0.0, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.01, 0.0,
                            0.0, 0.0, 0.0, 0.0, 0.0, 0.01]
