aruco_params:
  11:
    x: 4.352
    y: 6.368
    yaw: 0.0
  618:
    x: 4.402
    y: 7.358
    yaw: 0.0
  645:
    x: 0.0
    y: 0.0
    yaw: 0.0
  614:
    x: 4.38
    y: 4.56
    yaw: 0.0
  914:
    x: 1.0
    y: 1.0
    yaw: 0.0
