profile_name: home_windows
start_rviz: false

movement:
  enabled: true
  backend: fake
  max_speed: 0.8
  odom_rate: 30.0

imu:
  enabled: true
  backend: fake
  rate_hz: 30.0
  yaw_rate: 0.0
  static_tf_parent: base_link
  static_tf_child: bno055
  static_tf_xyzrpy: [0, 0, 0, 0, 0, 0]

localization:
  enabled: false
  camera_backend: disabled
  source: 0

ekf:
  enabled: true
  config: ekf.yaml

visualization:
  enabled: true
  backend: foxglove
  port: 8765
  address: 0.0.0.0
