profile_name: work_ubuntu_localization_test
start_rviz: false

robot_model:
  enabled: true

movement:
  enabled: false

imu:
  enabled: false

localization:
  enabled: true
  camera_backend: opencv
  source: 0
  config: calibration_ubuntu_test.yaml
  process_rate_hz: 30.0
  map_odom_publish_rate_hz: 30.0
  publish_map_to_base: true
  diagnostics_rate_hz: 1.0

marker_map:
  enabled: true
  config: marker_map_laptop_test.yaml
  diagnostics_rate_hz: 1.0

ekf:
  enabled: false

visualization:
  enabled: false
  backend: foxglove
  port: 8765
  address: 0.0.0.0

diagnostics:
  enabled: true
  publish_rate_hz: 1.0
