bno055:
  ros__parameters:
    ros_topic_prefix: "bno055/"
    connection_type: "uart"
    uart_port: "/dev/ttyUSB0"
    uart_baudrate: 115200
    uart_timeout: 0.1
    data_query_frequency: 100
    calib_status_frequency: 0.1
    frame_id: "imu"
    operation_mode: 0x0
    placement_axis_remap: "P0"
    acc_factor: 100.0
    mag_factor: 16000000.0
    gyr_factor: 900.0
    set_offsets: true # set to true to use offsets below
    offset_acc: [0xFFFC, 0x5, 0xFFEC]
    offset_mag: [0xFEDE, 0x16B, 0x3D]
    offset_gyr: [0xFFFE, 0xFFFF, 0x2]