name: Build and Push to GHCR

on:
  push:
    branches:
      - "clean-start"

permissions:
  contents: read
  packages: write

jobs:
  # Step 1: Filter changes to see if Dockerfile.base was modified
  filter:
    runs-on: ubuntu-latest
    outputs:
      base_changed: ${{ steps.filter.outputs.base }}
    steps:
      - uses: actions/checkout@v3
      - name: Check changes in Dockerfile.base
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            base:
              - 'Dockerfile.base'

  # Step 2: Build and push the base image only if Dockerfile.base changed
  build-base:
    if: ${{ needs.filter.outputs.base_changed == 'true' }}
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.base
          push: true
          tags: ghcr.io/swisscatplus/em_onrobot/em_robot_base:latest

  # Step 3: Build and push the derived image (always)
  build-derived:
    needs: [filter, build-base]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push derived image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/swisscatplus/em_onrobot/em_robot:latest
