name: Build and Push Derived Image

on:
  push:
    branches:
      - "clean-start"
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'entrypoint.sh'

permissions:
  contents: read
  packages: write

jobs:
  build-derived:
    if: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push derived image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: linux/arm64
          push: true
          tags: ghcr.io/swisscatplus/em_onrobot/em_robot:latest
