name: Builds and pushes the docker image on the organization's hub

on:
  push:
    branches: ['main']
env:
  REGISTRY: docker.io
  ORG: ${{ github.repository_owner }}
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: build-and-push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jcswisscat/em_onrobot:latest
