name: Builds and pushes the docker image on the organization's hub

on:
  push:
    branches: ['main']
env:
  REGISTRY: docker.io
  ORG: ${{ github.repository_owner }}
  
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: docker build --file ./SwissCat-on_robot/Dockerfile --no-cache -t jcswisscat/em_onrobot:$(date +%s)
      - name: login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{swisscat@epfl.ch}}
          password: ${{ARiS3h!u5gj#j}}
      - name: push
        run: docker image push jcswisscat/em_onrobot:$(date +%s)
