name: Builds and pushes the docker image on the organization's hub

on:
  push:
    branches: ['main']
env:
  REGISTRY: docker.io
  ORG: ${{ github.repository_owner }}
  
jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: "swisscat@epfl.ch"
          password: "ARiS3h!u5gj#j"
      - name: build-and-push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: jcswisscat/em_rpi:v0@sha256:baa91ecc9d39aa8aa94d17b1d284d6cbfa273fba79c4be0ee249c6b7cb83891f

